export type ExportState = {
  trade: string
  customer: { name: string; phone: string; email: string }
  vehicle: { year: string; make: string; model: string; mileage: string; vin: string; plate: string }
  property: { address: string; type: string }
  concerns: Array<{ description: string; priority: string; when_occurs?: string }>
  followUps: string[]
  notes: string
  sentiment: string
}

const DIV = '─'.repeat(42)

export function formatWorkOrder(s: ExportState): string {
  const lines: string[] = []
  const ln = (x: string) => lines.push(x)
  const blank = () => lines.push('')
  const section = (title: string) => { blank(); ln(DIV); ln(title); ln(DIV) }

  ln('WORK ORDER')
  ln(`Date: ${new Date().toLocaleDateString('en-US', { weekday: 'short', year: 'numeric', month: 'short', day: 'numeric' })}`)
  ln(`Trade: ${s.trade.toUpperCase()}`)
  ln(`Sentiment: ${s.sentiment}`)

  section('CUSTOMER')
  if (s.customer.name)  ln(`Name:  ${s.customer.name}`)
  if (s.customer.phone) ln(`Phone: ${s.customer.phone}`)
  if (s.customer.email) ln(`Email: ${s.customer.email}`)

  if (s.trade === 'auto') {
    const v = s.vehicle
    section('VEHICLE')
    const yr = [v.year, v.make, v.model].filter(Boolean).join(' ')
    if (yr)       ln(yr)
    if (v.mileage) ln(`Mileage: ${v.mileage}`)
    if (v.plate)   ln(`Plate:   ${v.plate}`)
    if (v.vin)     ln(`VIN:     ${v.vin}`)
  } else {
    const p = s.property
    section('PROPERTY')
    if (p.address) ln(`Address: ${p.address}`)
    if (p.type)    ln(`Type:    ${p.type}`)
  }

  const validConcerns = s.concerns.filter(c => c.description.trim())
  if (validConcerns.length > 0) {
    section('CONCERNS')
    validConcerns.forEach((c, i) => {
      ln(`${i + 1}. [${c.priority.toUpperCase()}] ${c.description}`)
      if (c.when_occurs) ln(`   When: ${c.when_occurs}`)
    })
  }

  const validFollowUps = s.followUps.filter(Boolean)
  if (validFollowUps.length > 0) {
    section('FOLLOW-UP QUESTIONS')
    validFollowUps.forEach((q, i) => ln(`${i + 1}. ${q}`))
  }

  if (s.notes.trim()) {
    section(s.trade === 'auto' ? 'ADVISOR NOTES' : 'TECH NOTES')
    ln(s.notes)
  }

  blank()
  ln('─'.repeat(42))
  ln('Generated by AutomatedIntake.app')

  return lines.join('\n')
}
